export const IS_LOADING = "IS LOADING";
export const FETCH_WEATHER_DATA = "FETCH_WEATHER_DATA";
export const SET_LENGTH_UNIT = "SET_LENGTH_UNIT";
export const SET_TEMPERATURE_UNIT = "SET_TEMPERATURE_UNIT";
export const SHOW_ERROR_MESSAGE = "SHOW_ERROR_MESSAGE";